create table category (
id integer generated by default as identity,
 name varchar(255) not null, 
 primary key (id));
 
 create table order_item (
 id integer generated by default as identity, quantity integer,
  order_id integer, product_id integer, primary key (id));
  
create table ORDERS (
 id integer generated by default as identity, 
 code integer not null,
 primary key (id));

create table order_client (client_id bigint, order_id integer not null, primary key (order_id));

create table orders_order_items (order_id integer not null, order_items_id integer not null);
  
create table role (id bigint generated by default as identity, name varchar(255), primary key (id));
  
create table user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id));

create table user (
user_id bigint generated by default as identity,
  created_date timestamp not null,
  display_name varchar(255),
  email varchar(255), 
  type varchar(20), 
  enabled BIT, 
  modified_date timestamp, 
  password varchar(255), 
  provider varchar(255), 
  provider_user_id varchar(255), 
  secret varchar(255), 
  primary key (user_id)
);

create table product (id integer generated by default as identity, active boolean, code varchar(255) not null, created_date date not null, description varchar(255), image_url varchar(255) not null, last_updated date, name varchar(255) not null, unit_in_stock integer, unit_price double not null, category_id integer not null, primary key (id));

alter table order_item add constraint FKt4dc2r9nbvbujrljv3e23iibt foreign key (order_id) references orders;

alter table order_item add constraint FK551losx9j75ss5d6bfsqvijna foreign key (product_id) references product;

alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;

alter table user_role add constraint FK7k6omm9osybsaema06aulfcj5 foreign key (role_id) references role;

alter table user_role add constraint FKddt2kyig2y9i09q3ks9k9uwaw foreign key (user_id) references user;
 
